//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoVIP.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int idLike { get; set; }
        public int idUser { get; set; }
        public int idProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
