//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoVIP.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int idSupply { get; set; }
        public int idManufacturer { get; set; }
        public int idCountry { get; set; }
        public int idSupplyCategory { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual SupplyCategory SupplyCategory { get; set; }
    }
}
